export const MODULES = [
    {
        id: 1,
        title_ru: 'Веб-интерфейс',
        title_en: 'Web interface',
        image: 'web',
        image_light: 'web_interfase_light',
        image_dark: 'web_interfase_dark',
        about_ru: 'Современный и интуитивно понятный интерфейс для работы с проектами, документами и данными. Обеспечивает удобную навигацию, быстрый поиск и доступ к актуальной информации в любое время.',
        about_en: 'A modern and intuitive interface for working with projects, documents and data. It provides convenient navigation, quick search and access to up-to-date information at any time.',
        features_ru: [
            "Удобная работа с проектами",
            "Гибкие настройки и фильтры",
            "Адаптивный дизайн для любых устройств",
            "Быстрый доступ к ключевой информации",
        ],
        features_en: [
            "Convenient work with projects",
            "Flexible settings and filters",
            "Responsive design for all devices",
            "Quick access to key information",
        ],
    },
    {
        id: 2,
        title_ru: 'Модуь ЭЦП',
        title_en: 'The EDS module',
        image: 'ecp',
        image_light: 'web_interfase_light',
        image_dark: 'web_interfase_dark',
        about_ru: 'Современный и интуитивно понятный интерфейс для работы с проектами, документами и данными. Обеспечивает удобную навигацию, быстрый поиск и доступ к актуальной информации в любое время.',
        about_en: 'A modern and intuitive interface for working with projects, documents and data. It provides convenient navigation, quick search and access to up-to-date information at any time.',
    },
    {
        id: 3,
        title_ru: 'Модуль корреспонденции',
        title_en: 'Correspondence module',
        image: 'corr',
        image_light: 'web_interfase_light',
        image_dark: 'web_interfase_dark',
        about_ru: 'Современный и интуитивно понятный интерфейс для работы с проектами, документами и данными. Обеспечивает удобную навигацию, быстрый поиск и доступ к актуальной информации в любое время.',
        about_en: 'A modern and intuitive interface for working with projects, documents and data. It provides convenient navigation, quick search and access to up-to-date information at any time.',
    },
    {
        id: 4,
        title_ru: 'Модуль заданий и планирования',
        title_en: 'The Tasks and Planning module',
        image: 'tasks',
        image_light: 'web_interfase_light',
        image_dark: 'web_interfase_dark',
        about_ru: 'Современный и интуитивно понятный интерфейс для работы с проектами, документами и данными. Обеспечивает удобную навигацию, быстрый поиск и доступ к актуальной информации в любое время.',
        about_en: 'A modern and intuitive interface for working with projects, documents and data. It provides convenient navigation, quick search and access to up-to-date information at any time.',
    },
    {
        id: 5,
        title_ru: 'Модуль ТУ и согласований',
        title_en: 'Technical specifications and approvals module',
        image: 'tachspec_approvals',
        image_light: 'web_interfase_light',
        image_dark: 'web_interfase_dark',
        about_ru: 'Современный и интуитивно понятный интерфейс для работы с проектами, документами и данными. Обеспечивает удобную навигацию, быстрый поиск и доступ к актуальной информации в любое время.',
        about_en: 'A modern and intuitive interface for working with projects, documents and data. It provides convenient navigation, quick search and access to up-to-date information at any time.',
    },
];

export const PROGRAMMS = [
    {
        id: 1,
        title: 'AutoCAD, AutoCAD Civil 3D, Indor Road',
        description_ru: 'Системы автоматизированного проектирования общего и специального назначения',
        description_en: 'Computer-aided design systems for general and special purposes',
        image: 'cads',
    },
    {
        id: 2,
        title: 'Word, Excel, PowerPoint',
        description_ru: 'Инструменты создания, редактирования и просмотра офисных документов',
        description_en: 'Tools for creating, editing, and viewing office documents',
        image: 'ms_office',
    },
    {
        id: 3,
        title: 'GIMP, FastStone Image Viewer',
        description_ru: 'Инструменты создания, редактирования и просмотра графических материалов',
        description_en: 'Tools for creating, editing, and viewing graphic materials',
        image: 'draw',
    },
    {
        id: 4,
        title: 'PDF Acrobat Reader DC, PDF-XChange Editor',
        description_ru: 'Инструменты базовой обработки и редактирования PDF-документов',
        description_en: 'Basic PDF document processing and editing tools',
        image: 'pdf',
    },
];
export const TASKS_SERVER = [
    {
        id: 1,
        name_ru: 'хранение проектной информации и документов;',
        name_en: 'storage of project information and documents;',
    },
    {
        id: 2,
        name_ru: 'обработка запросов от прикладных программ;',
        name_en: 'processing requests from application programs;',
    },
    {
        id: 3,
        name_ru: 'обеспечение доступа и разграничение прав пользователей;',
        name_en: 'ensuring access and differentiation of user rights;',
    },
    {
        id: 4,
        name_ru: 'контроль целостности данных;',
        name_en: 'data integrity control;',
    },
    {
        id: 5,
        name_ru: 'выполнение операций чтения и записи;',
        name_en: 'performing read and write operations;',
    },
    {
        id: 6,
        name_ru: 'обеспечение совместной работы пользователей;',
        name_en: 'ensuring user collaboration;',
    },
    {
        id: 7,
        name_ru: 'ведение истории изменений и журналирование операций.',
        name_en: 'maintaining a history of changes and logging operations.',
    },
];

export const NECESSARY = [
    {
        id: 1,
        icon: 'why_rights',
        title_ru: 'Система прав',
        title_en: 'The rights system',
        description_ru: 'Гибкая система разграничения прав доступа повышает безопасность и позволяет ограничивать просмотр и редактирование данных в соответствии с установленными ролями сотрудников. ',
        description_en: 'A flexible access control system increases security and allows you to restrict the viewing and editing of data in accordance with the established roles of employees.',
    },
    {
        id: 2,
        icon: 'why_saves',
        title_ru: 'Сохранность и хранение информации',
        title_en: 'Safety and storage of information',
        description_ru: 'Кроме того, использование разработанного нами програмного обеспеченья позволяет создать надежное хранилище информации, с возможностью резервного копирования, восстановления и  масштабирования системы по мере роста объема данных и количества пользователей.',
        description_en: 'In addition, using the software developed by us allows you to create a reliable information storage, with the ability to backup, restore and scale the system as the amount of data and the number of users grow.',
    },
    {
        id: 3,
        icon: 'why_risks',
        title_ru: 'Все риски при работе с данными при использовании традиционных файловых систем Windows',
        title_en: 'All the risks of working with data when using traditional Windows file systems',
        points: [
            { id: 1, 
                point_ru: 'Разрозненность, недостаточность и неполнота данных проекта', 
                point_en: 'Fragmentation, insufficiency and incompleteness of project data' 
            },
            { id: 2, 
                point_ru: 'Случайные или преднамеренные потери данных', 
                point_en: 'Accidental or intentional data loss' 
            },
            { id: 3, 
                point_ru: 'Противоречивость данных', 
                point_en: 'Inconsistency of data' 
            },
            { id: 4, 
                point_ru: 'Сложности при создании и ведении учета истории изменений документов', 
                point_en: 'Difficulties in creating and keeping records of the history of document changes' 
            },
            { id: 5, 
                point_ru: 'Несвоевременное внесение изменений в данные проекта', 
                point_en: 'Late introduction of changes to project data' 
            },
            { id: 6, 
                point_ru: 'Неконтролируемое внесение изменений в проектную документацию', 
                point_en: 'Uncontrolled modification of project documentation' 
            },
            { id: 7, 
                point_ru: 'Невозможность быстрого доступа к нужной информации', 
                point_en: 'Inability to quickly access the necessary information' 
            },
            { id: 8, 
                point_ru: 'Трудности при обработке информации, полученной от контрагентов', 
                point_en: 'Difficulties in processing information received from counterparties' 
            },
            { id: 9, 
                point_ru: 'Размывание ответственности при внесении изменений в проектную документацию и связанные с ней данные', 
                point_en: 'Blurring of responsibility when making changes to project documentation and related data' 
            },
            { id: 10, 
                point_ru: 'Зависимость компании от ключевых сотрудников, которые аккумулируют информацию', 
                point_en: "The company's dependence on key employees who accumulate information" 
            },
            { id: 11, 
                point_ru: 'Доступ к данным и возможность внесения изменений сотрудниками без соответствующих полномочий', 
                point_en: 'Access to data and the possibility of making changes by employees without appropriate authority' 
            },
        ]
    },
];

export const NEWS = [
    {
        id: 3,
        image: 'article1.jpg',
        time_ru: '07.07.2026 13:34',
        time_en: '07/07/2026, 13:34',
        title_ru: 'Новый архитектурный акцент города: современное здание с пешеходным переходом у станции „Технопарк“',
        title_en: 'A new architectural accent of the city: a modern building with a pedestrian crossing at the Technopark station',
        articles: [
            { id: 1, 
                article_ru: 'В районе станции метро «Технопарк» появилось выразительное современное здание, которое уже стало заметной частью городского пейзажа. Лаконичный дизайн, чёткие геометрические формы и масштабное панорамное остекление подчёркивают технологичный характер локации и гармонично вписываются в деловой контекст района.',
                article_en: 'An expressive modern building has appeared in the area of the Technopark metro station, which has already become a prominent part of the urban landscape. The laconic design, clear geometric shapes and large-scale panoramic glazing emphasize the technological nature of the location and harmoniously fit into the business context of the area.',
            },
            { id: 2, 
                article_ru: 'Ключевой особенностью объекта стал надземный пешеходный переход, соединяющий здание с транспортной инфраструктурой. Прозрачные ограждения и стеклянные панели сохраняют визуальную лёгкость конструкции, не перекрывая виды на прилегающую территорию. Благодаря такому решению путь пассажиров стал удобнее и безопаснее, а сам переход — полноценным элементом городской среды.',
                article_en: "The key feature of the facility is an above-ground pedestrian crosswalk connecting the building to the transport infrastructure. Transparent fences and glass panels preserve the visual lightness of the structure without blocking the views of the surrounding area. Thanks to this solution, the passengers' journey has become more convenient and safer, and the crossing itself has become a full—fledged element of the urban environment.",
            },
            { id: 3, 
                article_ru: 'На фото — фрагмент фасада и входной зоны в «мягком» вечернем свете: именно в это время контраст между тёплым уличным освещением и тёмным остеклением раскрывает выразительность архитектуры. На переднем плане — пешеходная зона с ровным мощением и аккуратно оформленным газоном, что подчёркивает продуманность благоустройства.',
                article_en: 'The photo shows a fragment of the facade and the entrance area in the "soft" evening light: it is at this time that the contrast between warm street lighting and dark glazing reveals the expressiveness of architecture. In the foreground is a pedestrian zone with smooth paving and a neatly decorated lawn, which emphasizes the thoughtfulness of landscaping.',
            },
            { id: 4, 
                article_ru: 'Проект демонстрирует, как функциональность и эстетика могут работать вместе: здание не только отвечает современным требованиям к инфраструктуре, но и задаёт новый стандарт для общественных пространств в городе.',
                article_en: 'The project demonstrates how functionality and aesthetics can work together: the building not only meets modern infrastructure requirements, but also sets a new standard for public spaces in the city.',
            },
        ],
    },
    {
        id: 2,
        image: 'article2.jpg',
        time_ru: '06.07.2026 19:05',
        time_en: '06/07/2026, 19:05',
        title_ru: 'Развязка на пересечении МКАД с Липецкой улицей: как масштабный транспортный узел меняет ритм южной части Москвы',
        title_en: 'Interchange at the intersection of MKAD and Lipetsk street: how a large-scale transport hub is changing the rhythm of the southern part of Moscowz',
        articles: [
            { id: 1,
                article_ru: 'На фото — фрагмент одной из ключевых транспортных артерий столицы: многоуровневая развязка на пересечении МКАД с Липецкой улицей. Кадр сделан в «золотой час» — мягкий закатный свет подчёркивает протяжённость эстакад, ритмику опор и масштаб дорожной сети, которая ежедневно пропускает десятки тысяч автомобилей.',
                article_en: 'The photo shows a fragment of one of the key transport arteries of the capital: a multi—level interchange at the intersection of MKAD and Lipetsk Street. The shot was taken during the "golden hour" — the soft sunset light highlights the length of the overpasses, the rhythm of the pillars and the scale of the road network, which passes tens of thousands of cars every day.',
            },
            { id: 2,
                article_ru: 'Перед нами не просто участок трассы, а продуманный транспортный узел: направленные съезды и эстакады разводят потоки по разным уровням, снижая риск пересечений и заторов. Многополосная дорога, чёткая разметка, современные ограждения и уличное освещение формируют безопасную и предсказуемую среду для водителей. На переднем плане — плавный изгиб насыпи и подпорная стенка: такие детали показывают, насколько тщательно проектируется даже «вспомогательная» инфраструктура.',
                article_en: 'This is not just a section of highway, but a well-thought-out transport hub: directional ramps and overpasses separate flows at different levels, reducing the risk of intersections and congestion. A multi-lane road, clear markings, modern fences and street lighting create a safe and predictable environment for drivers. In the foreground, there is a smooth curve of the embankment and a retaining wall: such details show how carefully even the "auxiliary" infrastructure is being designed.',
            },
            { id: 3,
                article_ru: 'На фоне — городской силуэт: высотные жилые комплексы и плотная застройка, типичная для южных районов Москвы. Зелёные массивы по обе стороны дороги напоминают о важности баланса между транспортной нагрузкой и экологией города.',
                article_en: 'There is an urban silhouette against the background: high—rise residential complexes and dense buildings typical of the southern districts of Moscow. The green spaces on both sides of the road remind of the importance of balancing the traffic load and the ecology of the city.',
            },
            { id: 4,
                article_ru: 'Эта развязка — пример системной модернизации МКАД: вместо устаревших «клеверных» пересечений появляются узлы с направленными съездами, где машины движутся без лишних манёвров и резких торможений. В результате растёт пропускная способность, сокращаются пробки, а поездки становятся комфортнее и безопаснее.',
                article_en: 'This interchange is an example of a systemic modernization of the MKAD: instead of outdated "clover" intersections, nodes with directional exits appear, where cars move without unnecessary maneuvers and sudden braking. As a result, capacity increases, traffic jams decrease, and trips become more comfortable and safer.',
            },
            { id: 5,
                article_ru: 'Снимок удачно передаёт динамику мегаполиса: плотный, но упорядоченный поток транспорта, чёткая геометрия инженерных сооружений и переход от индустриального ритма дороги к спокойной зелени на склонах. Именно такие кадры помогают показать, как крупные инфраструктурные проекты становятся частью привычного городского пейзажа и улучшают повседневную жизнь сотен тысяч людей.',
                article_en: 'The image successfully conveys the dynamics of the metropolis: dense but orderly traffic flow, clear geometry of engineering structures and the transition from the industrial rhythm of the road to calm greenery on the slopes. It is such footage that helps to show how large infrastructure projects become part of the familiar urban landscape and improve the daily lives of hundreds of thousands of people.',
            },
        ],
    },
    {
        id: 1,
        image: 'article3.jpg',
        time_ru: '06.07.2026 10:00',
        time_en: '06/07/2026, 10:00',
        title_ru: 'Современность в деталях: лаконичный фасад и пешеходные связи у станции „Технопарк“',
        title_en: 'Modernity in detail: laconic facade and pedestrian connections at the Technopark station',
        articles: [
            { id: 1,
                article_ru: 'На фото — фрагмент городской застройки у станции метро «Технопарк»: здание с выразительным минималистичным фасадом и строгой вертикальной ритмикой. Акцент в архитектуре сделан на контрасте матовых светло‑серых панелей и узких высоких витражей: такие окна не только придают объёму графичность, но и обеспечивают хорошую инсоляцию внутренних помещений.',
                article_en: 'The photo shows a fragment of urban development near the Technopark metro station: a building with an expressive minimalistic facade and strict vertical rhythm. The architectural emphasis is on the contrast of matte light gray panels and narrow high stained glass windows.: such windows not only add graphics to the volume, but also provide good indoor sunlight.',
            },
            { id: 2,
                article_ru: 'Характерная деталь — крытый переход, соединяющий корпуса: он формирует удобную пешеходную связь и защищает людей от осадков и ветра. На снимке хорошо читается логика благоустройства: аккуратные газоны, молодые деревья, чёткие линии мощения и лаконичные уличные светильники поддерживают общий сдержанный стиль квартала.',
                article_en: 'A characteristic detail is the covered walkway connecting the buildings: it forms a convenient pedestrian connection and protects people from precipitation and wind. The picture clearly shows the logic of landscaping: Neat lawns, young trees, clear paving lines and laconic street lights support the overall restrained style of the neighborhood.',
            },
            { id: 3,
                article_ru: 'На фоне — более высокий жилой дом с тёплым терракотовым фасадом: такое соседство подчёркивает разнообразие городской среды и показывает, как современные общественные здания встраиваются в уже сложившуюся застройку. В правой части кадра — группа прохожих: это добавляет снимку динамики и масштаба, наглядно демонстрируя, что пространство действительно «работает» на горожан.',
                article_en: 'Against the background is a taller apartment building with a warm terracotta facade: this neighborhood highlights the diversity of the urban environment and shows how modern public buildings are integrated into existing buildings. On the right side of the frame is a group of passersby: this adds dynamics and scale to the snapshot, clearly demonstrating that the space really "works" for the townspeople.',
            },
            { id: 4,
                article_ru: 'Здание выглядит как часть продуманного городского узла: здесь сочетаются функциональность (пешеходные маршруты, понятная навигация), эстетика (чистые линии, качественные материалы) и внимание к деталям (озеленение, уличная мебель). Такой подход к проектированию делает район не только удобным для транзита, но и приятным для повседневной жизни — и именно это всё чаще становится главным критерием оценки новых городских пространств.',
                article_en: 'The building looks like part of a well-thought-out urban hub: it combines functionality (walking routes, clear navigation), aesthetics (clean lines, high-quality materials) and attention to detail (landscaping, outdoor furniture). This approach to design makes the area not only convenient for transit, but also pleasant for everyday life — and this is increasingly becoming the main criterion for evaluating new urban spaces.',
            },
        ],
    },
];